const GENERATION = {
    FETCH: 'GENERATION_FETCH',
    FETCH_ERROR: 'GENERATION_FETCH_ERROR',
    FETCH_SUCCESS: 'GENERATION_FETCH_SUCCESS'
};

const SLIME = {
    FETCH: 'SLIME_FETCH',
    FETCH_ERROR: 'SLIME_FETCH_ERROR',
    FETCH_SUCCESS: 'SLIME_FETCH_SUCCESS'
}

const ACCOUNT = {
    FETCH: 'ACCOUNT_FETCH',
    FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
    FETCH_SUCCESS: 'ACCOUNT_FETCH_SUCCESS',
    FETCH_LOGOUT: 'ACCOUNT_FETCH_LOGOUT_SUCCESS',
    FETCH_AUTHENTICATED_SUCCESS: 'ACCOUNT_FETCH_AUTHENTICATED_SUCCESS'
}

export {GENERATION, SLIME, ACCOUNT};